export const NATIONALITIES = {
  AU: { name: "Australian", color: "magenta" },
  BR: { name: "Brazilian", color: "red" },
  CA: { name: "Canadian", color: "volcano" },
  CH: { name: "Swiss", color: "orange" },
  DE: { name: "German", color: "#1F48FF" },
  DK: { name: "Danish", color: "lime" },
  ES: { name: "Spanish", color: "green" },
  FI: { name: "Finnish", color: "cyan" },
  FR: { name: "French", color: "blue" },
  GB: { name: "British", color: "geekblue" },
  IE: { name: "Irish", color: "purple" },
  IR: { name: "Iranian", color: "#f50" },
  NO: { name: "Norwegian", color: "#2db7f5" },
  NL: { name: "Dutch", color: "#87d068" },
  NZ: { name: "New Zealander", color: "#9e1068" },
  TR: { name: "Turkish", color: "#A37800" },
  US: { name: "American", color: "#A94C7A" },
};

export const nationalitiesData = [
  { id: 1, label: "AU", value: "Australian" },
  { id: 2, label: "BR", value: "Brazilian" },
  { id: 3, label: "CA", value: "Canadian" },
  { id: 4, label: "CH", value: "Swiss" },
  { id: 5, label: "DE", value: "German" },
  { id: 6, label: "DK", value: "Danish" },
  { id: 7, label: "ES", value: "Spanish" },
  { id: 8, label: "FI", value: "Finnish" },
  { id: 9, label: "FR", value: "French" },
  { id: 10, label: "GB", value: "British" },
  { id: 11, label: "IE", value: "Irish" },
  { id: 12, label: "IR", value: "Iranian" },
  { id: 13, label: "NO", value: "Norwegian" },
  { id: 14, label: "NL", value: "Dutch" },
  { id: 15, label: "NZ", value: "New Zealander" },
  { id: 16, label: "TR", value: "Turkish" },
  { id: 17, label: "US", value: "American" },
];
